# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_video_widget(object):
    def setupUi(self, video_widget):
        video_widget.setObjectName("video_widget")
        video_widget.resize(1200, 801)
        self.horizontalLayout = QtWidgets.QHBoxLayout(video_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ResolutionLabel = QtWidgets.QLabel(video_widget)
        self.ResolutionLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.ResolutionLabel.setFont(font)
        self.ResolutionLabel.setObjectName("ResolutionLabel")
        self.verticalLayout_3.addWidget(self.ResolutionLabel)
        self.FrameView = QtWidgets.QGraphicsView(video_widget)
        self.FrameView.setMinimumSize(QtCore.QSize(480, 360))
        self.FrameView.setObjectName("FrameView")
        self.verticalLayout_3.addWidget(self.FrameView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.backKeyBtn = QtWidgets.QPushButton(video_widget)
        self.backKeyBtn.setMinimumSize(QtCore.QSize(50, 30))
        self.backKeyBtn.setMaximumSize(QtCore.QSize(50, 30))
        self.backKeyBtn.setObjectName("backKeyBtn")
        self.horizontalLayout_3.addWidget(self.backKeyBtn)
        self.playBtn = QtWidgets.QPushButton(video_widget)
        self.playBtn.setMinimumSize(QtCore.QSize(50, 30))
        self.playBtn.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.playBtn.setFont(font)
        self.playBtn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.playBtn.setIconSize(QtCore.QSize(20, 20))
        self.playBtn.setObjectName("playBtn")
        self.horizontalLayout_3.addWidget(self.playBtn)
        self.forwardKeyBtn = QtWidgets.QPushButton(video_widget)
        self.forwardKeyBtn.setMinimumSize(QtCore.QSize(50, 30))
        self.forwardKeyBtn.setMaximumSize(QtCore.QSize(50, 30))
        self.forwardKeyBtn.setObjectName("forwardKeyBtn")
        self.horizontalLayout_3.addWidget(self.forwardKeyBtn)
        self.frameSlider = QtWidgets.QSlider(video_widget)
        self.frameSlider.setMinimumSize(QtCore.QSize(300, 30))
        self.frameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.frameSlider.setObjectName("frameSlider")
        self.horizontalLayout_3.addWidget(self.frameSlider)
        self.frameNumLabel = QtWidgets.QLabel(video_widget)
        self.frameNumLabel.setMinimumSize(QtCore.QSize(20, 20))
        self.frameNumLabel.setObjectName("frameNumLabel")
        self.horizontalLayout_3.addWidget(self.frameNumLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.setStretch(1, 4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.settingGroupbox = QtWidgets.QGroupBox(video_widget)
        self.settingGroupbox.setMinimumSize(QtCore.QSize(350, 400))
        self.settingGroupbox.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.settingGroupbox.setFont(font)
        self.settingGroupbox.setObjectName("settingGroupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settingGroupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FileGroupbox = QtWidgets.QGroupBox(self.settingGroupbox)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.FileGroupbox.setFont(font)
        self.FileGroupbox.setObjectName("FileGroupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.FileGroupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.NameLabel = QtWidgets.QLabel(self.FileGroupbox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.NameLabel.setFont(font)
        self.NameLabel.setObjectName("NameLabel")
        self.horizontalLayout_6.addWidget(self.NameLabel)
        self.videoNameLabel = QtWidgets.QLabel(self.FileGroupbox)
        self.videoNameLabel.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.videoNameLabel.setFont(font)
        self.videoNameLabel.setText("")
        self.videoNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.videoNameLabel.setObjectName("videoNameLabel")
        self.horizontalLayout_6.addWidget(self.videoNameLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FPSLabel = QtWidgets.QLabel(self.FileGroupbox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.FPSLabel.setFont(font)
        self.FPSLabel.setObjectName("FPSLabel")
        self.horizontalLayout_2.addWidget(self.FPSLabel)
        self.FPSInfoLabel = QtWidgets.QLabel(self.FileGroupbox)
        self.FPSInfoLabel.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.FPSInfoLabel.setFont(font)
        self.FPSInfoLabel.setText("")
        self.FPSInfoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FPSInfoLabel.setObjectName("FPSInfoLabel")
        self.horizontalLayout_2.addWidget(self.FPSInfoLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.loadOriginalVideoBtn = QtWidgets.QPushButton(self.FileGroupbox)
        self.loadOriginalVideoBtn.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.loadOriginalVideoBtn.setFont(font)
        self.loadOriginalVideoBtn.setObjectName("loadOriginalVideoBtn")
        self.gridLayout.addWidget(self.loadOriginalVideoBtn, 1, 0, 1, 1)
        self.loadProcessedVideoBtn = QtWidgets.QPushButton(self.FileGroupbox)
        self.loadProcessedVideoBtn.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.loadProcessedVideoBtn.setFont(font)
        self.loadProcessedVideoBtn.setObjectName("loadProcessedVideoBtn")
        self.gridLayout.addWidget(self.loadProcessedVideoBtn, 2, 0, 1, 1)
        self.startCodeBtn = QtWidgets.QPushButton(self.FileGroupbox)
        self.startCodeBtn.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.startCodeBtn.setFont(font)
        self.startCodeBtn.setObjectName("startCodeBtn")
        self.gridLayout.addWidget(self.startCodeBtn, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.FileGroupbox)
        self.DisplayGroupBox = QtWidgets.QGroupBox(self.settingGroupbox)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.DisplayGroupBox.setFont(font)
        self.DisplayGroupBox.setObjectName("DisplayGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.DisplayGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.showSkeletonCheckBox = QtWidgets.QCheckBox(self.DisplayGroupBox)
        self.showSkeletonCheckBox.setChecked(False)
        self.showSkeletonCheckBox.setObjectName("showSkeletonCheckBox")
        self.gridLayout_2.addWidget(self.showSkeletonCheckBox, 0, 0, 1, 1)
        self.showBboxCheckBox = QtWidgets.QCheckBox(self.DisplayGroupBox)
        self.showBboxCheckBox.setCheckable(True)
        self.showBboxCheckBox.setChecked(False)
        self.showBboxCheckBox.setObjectName("showBboxCheckBox")
        self.gridLayout_2.addWidget(self.showBboxCheckBox, 0, 1, 1, 1)
        self.selectCheckBox = QtWidgets.QCheckBox(self.DisplayGroupBox)
        self.selectCheckBox.setObjectName("selectCheckBox")
        self.gridLayout_2.addWidget(self.selectCheckBox, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.DisplayGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.settingGroupbox)

        self.retranslateUi(video_widget)
        QtCore.QMetaObject.connectSlotsByName(video_widget)

    def retranslateUi(self, video_widget):
        _translate = QtCore.QCoreApplication.translate
        video_widget.setWindowTitle(_translate("video_widget", "Form"))
        self.ResolutionLabel.setText(_translate("video_widget", "(0, 0) - "))
        self.backKeyBtn.setText(_translate("video_widget", "<<"))
        self.playBtn.setText(_translate("video_widget", "▶︎"))
        self.forwardKeyBtn.setText(_translate("video_widget", ">>"))
        self.frameNumLabel.setText(_translate("video_widget", "0/0"))
        self.settingGroupbox.setTitle(_translate("video_widget", "2D 關節點"))
        self.FileGroupbox.setTitle(_translate("video_widget", "檔案"))
        self.NameLabel.setText(_translate("video_widget", "檔名:"))
        self.FPSLabel.setText(_translate("video_widget", "FPS:"))
        self.loadOriginalVideoBtn.setText(_translate("video_widget", "載入原始影片"))
        self.loadProcessedVideoBtn.setText(_translate("video_widget", "載入處理過的影片"))
        self.startCodeBtn.setText(_translate("video_widget", "處理和儲存"))
        self.DisplayGroupBox.setTitle(_translate("video_widget", "顯示資訊"))
        self.showSkeletonCheckBox.setText(_translate("video_widget", "人體骨架"))
        self.showBboxCheckBox.setText(_translate("video_widget", "人物框"))
        self.selectCheckBox.setText(_translate("video_widget", "選擇人"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    video_widget = QtWidgets.QWidget()
    ui = Ui_video_widget()
    ui.setupUi(video_widget)
    video_widget.show()
    sys.exit(app.exec_())
